name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: 'itsmattkc/msvc420'
        path: msvc420

    - name: Build wrappers
      shell: cmd
      run: |
        call .\msvc420\bin\VCVARS32.BAT x86
        cd qt-3.3.x-p8
        set QTDIR="d:\a\qt3win\qt3win\qt-3.3.x-p8\bin"
        set PATH=%QTDIR%\bin;%PATH%
        dir
        pconfigure.bat
        configure-msvc.bat

